# Generated by Django 5.2.4 on 2025-08-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stattsys', '0003_alter_attendance_student_alter_student_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='section',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
